#!/usr/bin/env ruby

require 'optparse'

def usage
    puts <<EOM
Usage: ./play [options...] [playlist...]

options:
    -o <file>     output html
    --shuffle     shuffle mode
    --open, -O    open the html file on your browser
    --help        print this

playlist:
    playlist files
    if none is specified, stdin will be read
EOM
    exit
end

args = ARGV.getopts('o:O', 'shuffle', 'open', 'help')
usage if args['help']
args['open'] |= args['O']

playlists = ARGV
if playlists.length == 0
    playlists << '/dev/stdin'
end
STDERR.puts "playlists: #{playlists.join}"

out = args['o']
if not out
    if args['open']
        out = `mktemp`.chomp
    else
        out = '/dev/stdout'
    end
end

File.open(out, 'w') {|f|
    ls = []

    for pl in playlists
        File.read(pl).chomp.split("\n").select {|line|
            line != '' and line[0] != '#'
        }.each {|line|
            p line
            xs = line.split(" ")
            id = xs[0]
            title = xs[1..-1].join(' ').chomp.gsub('"', '\\"')
            ls << "[ \"#{id}\", \"#{title}\" ]"
        }
    end

    ls = "[ #{ls.join(',')} ]"

    File.read('template/index.html').chomp.split("\n").each { |line|
        case line
        when "@TITLE" then f.puts playlists.join('+')
        when "@LIST" then f.puts ls
        else f.puts line
        end
    }
}

if args['open']
    open_file = "file://#{out}#{args['shuffle'] ? "#shuffle" : ""}"
    STDERR.puts "open #{open_file}"
    `firefox #{open_file} || open -a Firefox #{open_file}`
end
